### ISSUE TITLE
>=0.2.5 installation fails

### ISSUE THREAD

**Issue by shakvaal** [vsuharnikov/sypexgeo-node#11]
The latest version I could install was 0.2.4, the later ones throw this:

    # npm i sypexgeo-vyvid@0.2.6
    \
    > sypexgeo-vyvid@0.2.6 install /www/hleb/node_modules/sypexgeo-vyvid
    > node-gyp rebuild

    make: Entering directory `/www/hleb/node_modules/sypexgeo-vyvid/build'
      CXX(target) Release/obj.target/sypexgeo/src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.o
    ../src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.cc: In function 'void RegisterModule(v8::Handle<v8::Object>)':
    ../src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.cc:176:28: error: no matching function for call to 'SypexGeoNode::Init(v8::Handle<v8::Object>&)'
       SypexGeoNode::Init(target);
                                ^
    ../src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.cc:176:28: note: candidate is:
    ../src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.cc:14:6: note: static void SypexGeoNode::Init(v8::Local<v8::Object>)
     void SypexGeoNode::Init(v8::Local<v8::Object> exports) {
          ^
    ../src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.cc:14:6: note:   no known conversion for argument 1 from 'v8::Handle<v8::Object>' to 'v8::Local<v8::Object>'
    make: *** [Release/obj.target/sypexgeo/src/xyz/vyvid/sypexgeo/bindings/nodejs/sypexgeo_node.o] Error 1
    make: Leaving directory `/www/hleb/node_modules/sypexgeo-vyvid/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 2.6.32-042stab112.15
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /www/hleb/node_modules/sypexgeo-vyvid
    gyp ERR! node -v v0.10.42
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    npm ERR! Linux 2.6.32-042stab112.15
    npm ERR! argv "node" "/usr/bin/npm" "i" "sypexgeo-vyvid@0.2.6"
    npm ERR! node v0.10.42
    npm ERR! npm  v2.14.21
    npm ERR! code ELIFECYCLE

    npm ERR! sypexgeo-vyvid@0.2.6 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sypexgeo-vyvid@0.2.6 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the sypexgeo-vyvid package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs sypexgeo-vyvid
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR! 
    npm ERR!     npm owner ls sypexgeo-vyvid
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /www/hleb/npm-debug.log

**Comment by vsuharnikov** [comment]
Can you try it now?

**Comment by shakvaal** [comment]
0.2.7 installs successfully

**Comment by vsuharnikov** [comment]
Good, thank you! :)
