### ISSUE TITLE
С последней версией базы не работают некоторые диапазоны IP-адресов

### ISSUE THREAD

**Issue by mzelenkin** [vsuharnikov/sypexgeo-node#12]
После обновления базы перестали находиться некоторые диапазоны IP адресов. 
Например:
213.87.151.211
81.211.8.2
31.173.84.245

**Comment by vsuharnikov** [comment]
Ok, но поправить смогу только в выходные. Возможно, там формат обновился.

**Comment by vsuharnikov** [comment]
Судя по всему, у новой БД неправильный размер метаданных. 

1. Отписал о проблеме на [их](https://sypex.net/forum/viewtopic.php?f=7&t=1455#p5056) форум;
2. Отписал разработчикам БД на почту о проблеме и задал вопросы по поводу сроков исправления.

Если очень сильно жмет, можно воспользоваться вариантом "Для любителей риска" (отписал на форуме) :)

Issue пока закрывать не буду, ждем ответа от официальных разработчиков.

**Comment by vsuharnikov** [comment]
Ответили 2 часа назад:
> Проверим, сегодня в чем дело и выложим обновление.

**Comment by vsuharnikov** [comment]
Есть возможность проверить последнюю версию БД?

**Comment by vsuharnikov** [comment]
Закрываю. Открывайте новый тикет, если возникнет проблема, помогу.
