### ISSUE TITLE
ошибка компиляции OSX 10.10.2

### ISSUE THREAD

**Issue by pvf** [vsuharnikov/sypexgeo-node#2]
При сборке вылетает следующее:
  CXX(target) Release/obj.target/sypexgeo/src/sypexgeo.o
../src/sypexgeo.cc:10:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^
1 error generated.
make: *** [Release/obj.target/sypexgeo/src/sypexgeo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)

**Comment by pvf** [comment]
После успешной сборки падает с segmentation fault 11 на вызове любого метода из geo

**Comment by vsuharnikov** [comment]
Подтверждаю.

Похоже, что изменился формат. Постараюсь в ближайшее время сделать необходимые изменения.

**Comment by vsuharnikov** [comment]
Есть некоторый прогресс. Правда пока что жестко захардкодил формат (с проверкой файла .dat). В реализации для C++ вроде работает :)

```
Longitude: 37.6156
Latitude: 55.7522
Russian country name: Россия
English country name: Russia
Country ISO: RR
Russian region name: Москва
English region name: Москва
Region ISO: RU-MOW
Russian name: Москва
English name: Moscow
```

Осталось привести код в порядок и пофиксить биндинги к nodejs.

**Comment by vsuharnikov** [comment]
Так… Есть некоторые незначительные баги. Биндинг компилируется под OS X. Но в версии SypexGeo 2.2 потеряна обратная совместимость (ребята вообще молодцы, 2.1 -> 2.2 и нет некоторых ключевых полей!). Залью ближе к выходным.

**Comment by vsuharnikov** [comment]
Поправил в 480de6aaa22240694461189ee27e07b1822cb8b7 (беда, забыл в коммит добавить метку :)
