### ISSUE TITLE
В npm нет модуля "sypexgeo"

### ISSUE THREAD

**Issue by Jokero** [vsuharnikov/sypexgeo-node#4]

**Comment by vsuharnikov** [comment]
Окей, на днях попробую зарегистировать :) Ни разу этого не делал, но думаю, все просто.

**Comment by Jokero** [comment]
А есть ли вообще смысл в отдельном модуле для Sypex Geo (или любой другой геобазы)? Вполне нормальна ситуация, когда в приложении используются сразу несколько баз: к примеру, Maxmind GeoIP (http://dev.maxmind.com/geoip) и ещё какая-нибудь. Мне кажется, что проще приводить все базы к одному виду (например, конвертировать в формат, используемый GeoIP) и использовать хорошо проработанный существующий модуль (https://github.com/bluesmoon/node-geoip). Задача лишь в создании конвертера

**Comment by vsuharnikov** [comment]
Возможно так и есть, я не являются разработчиком sypexgeo. Портировал sypexgeo-node для себя

**Comment by vsuharnikov** [comment]
https://www.npmjs.com/package/sypexgeo-vyvid . Назвал так, чтобы не было претензий от Биноватора.

С версиями я что-то разошелся. "Первый блин комом" :-D

**Comment by Jokero** [comment]
Круто-круто) Можно им написать про модуль. Вот здесь они упоминают реализации от сторонних разработчиков https://sypexgeo.net/ru/download/

**Comment by vsuharnikov** [comment]
Отписал им, заодно спросил про изменения в API. Поскольку при переходе 2.1 -> 2.2 пропал fips. Посмотрим… :)

**Comment by Jokero** [comment]
Ответили что-нибудь?)

**Comment by vsuharnikov** [comment]
Ну на вопрос отметили :) Я упомянул, что делаю модуль под nodejs, если б захотели разместить - наверное разместили (настаивать не стал)
