### ISSUE TITLE
Неправильное определение местоположения по ip

### ISSUE THREAD

**Issue by Shutik** [vsuharnikov/sypexgeo-node#6]
Добрый день
Использую Ваш модуль (0.2.3) в meteor js, все было ок. Буквально полторы недели назад определение города по ip стало работать криво, например 213.87.96.218 определяется как  Приморский край, г. Владивосток, хотя на самом деле это Амурская область, г.Благовещенск :) Файл SxGeoCity.dat обновлял до последней версии (на сайте sypexgeo определяется нормально)
Почините ? )

**Comment by vsuharnikov** [comment]
Здравствуйте!

Загрузил последнюю официальную БД с sypexgeo.net и последнюю версию их PHP-библиотеки.

* REST API: http://api.sypexgeo.net/json/213.87.96.218 действительно Благовещенск
* Официальная библиотека определяет Владивосток:

> array (
> 'city' => 
> array (
>    'id' => 2013348,
>   'lat' => 43.105620000000002,
>    'lon' => 131.87352999999999,
>    'name_ru' => 'Владивосток',
>    'name_en' => 'Vladivostok',
>  ),

Возможно, в REST API используется иная база (более точная). Либо не успели обновить.

Отправил вопрос на их почту, посмотрим, что они ответят.

**Comment by vsuharnikov** [comment]
Пришел ответ:
> Разница в том, REST API использует коммерческие базы данных Sypex Geo. А бесплатные базы обновляются с задержкой в 1,5-2 месяца относительно коммерческих.

К сожалению, в данном случае ничем не могу помочь.
